#include "vm.h"

int sys_Obj__allocSize__();
void sys_Obj_trap_v(fr_Env env, void *param, void *ret);
void sys_Obj_isImmutable_v(fr_Env env, void *param, void *ret);
void sys_Enum_doFromStr_v(fr_Env env, void *param, void *ret);
int sys_Array__allocSize__();
void sys_Array_make_v(fr_Env env, void *param, void *ret);
void sys_Array_size_v(fr_Env env, void *param, void *ret);
void sys_Array_get_v(fr_Env env, void *param, void *ret);
void sys_Array_set_v(fr_Env env, void *param, void *ret);
void sys_Array_realloc_v(fr_Env env, void *param, void *ret);
void sys_Array_arraycopy_v(fr_Env env, void *param, void *ret);
void sys_Array_fill_v(fr_Env env, void *param, void *ret);
void sys_Array_finalize_v(fr_Env env, void *param, void *ret);
int sys_Bool__allocSize__();
void sys_Bool_equals_v(fr_Env env, void *param, void *ret);
void sys_Bool_not__v(fr_Env env, void *param, void *ret);
void sys_Bool_and__v(fr_Env env, void *param, void *ret);
void sys_Bool_or__v(fr_Env env, void *param, void *ret);
void sys_Bool_xor__v(fr_Env env, void *param, void *ret);
int sys_Float__allocSize__();
void sys_Float_makeBits_v(fr_Env env, void *param, void *ret);
void sys_Float_makeBits32_v(fr_Env env, void *param, void *ret);
void sys_Float_fromStr_v(fr_Env env, void *param, void *ret);
void sys_Float_random_v(fr_Env env, void *param, void *ret);
void sys_Float_equals_v(fr_Env env, void *param, void *ret);
void sys_Float_isNaN_v(fr_Env env, void *param, void *ret);
void sys_Float_negate_v(fr_Env env, void *param, void *ret);
void sys_Float_mult_v(fr_Env env, void *param, void *ret);
void sys_Float_multInt_v(fr_Env env, void *param, void *ret);
void sys_Float_div_v(fr_Env env, void *param, void *ret);
void sys_Float_divInt_v(fr_Env env, void *param, void *ret);
void sys_Float_mod_v(fr_Env env, void *param, void *ret);
void sys_Float_modInt_v(fr_Env env, void *param, void *ret);
void sys_Float_plus_v(fr_Env env, void *param, void *ret);
void sys_Float_plusInt_v(fr_Env env, void *param, void *ret);
void sys_Float_minus_v(fr_Env env, void *param, void *ret);
void sys_Float_minusInt_v(fr_Env env, void *param, void *ret);
void sys_Float_bits_v(fr_Env env, void *param, void *ret);
void sys_Float_bits32_v(fr_Env env, void *param, void *ret);
void sys_Float_toStr_v(fr_Env env, void *param, void *ret);
void sys_Float_toInt_v(fr_Env env, void *param, void *ret);
void sys_Float_toLocale_v(fr_Env env, void *param, void *ret);
int sys_Func__allocSize__();
void sys_Func_call_v(fr_Env env, void *param, void *ret);
void sys_BindFunc_call_v(fr_Env env, void *param, void *ret);
int sys_Int__allocSize__();
void sys_Int_fromStr_v(fr_Env env, void *param, void *ret);
void sys_Int_random_v(fr_Env env, void *param, void *ret);
void sys_Int_privateMake_v(fr_Env env, void *param, void *ret);
void sys_Int_equals_v(fr_Env env, void *param, void *ret);
void sys_Int_compare_v(fr_Env env, void *param, void *ret);
void sys_Int_negate_v(fr_Env env, void *param, void *ret);
void sys_Int_increment_v(fr_Env env, void *param, void *ret);
void sys_Int_decrement_v(fr_Env env, void *param, void *ret);
void sys_Int_mult_v(fr_Env env, void *param, void *ret);
void sys_Int_multFloat_v(fr_Env env, void *param, void *ret);
void sys_Int_div_v(fr_Env env, void *param, void *ret);
void sys_Int_divFloat_v(fr_Env env, void *param, void *ret);
void sys_Int_mod_v(fr_Env env, void *param, void *ret);
void sys_Int_modFloat_v(fr_Env env, void *param, void *ret);
void sys_Int_plus_v(fr_Env env, void *param, void *ret);
void sys_Int_plusFloat_v(fr_Env env, void *param, void *ret);
void sys_Int_minus_v(fr_Env env, void *param, void *ret);
void sys_Int_minusFloat_v(fr_Env env, void *param, void *ret);
void sys_Int_not__v(fr_Env env, void *param, void *ret);
void sys_Int_and__v(fr_Env env, void *param, void *ret);
void sys_Int_or__v(fr_Env env, void *param, void *ret);
void sys_Int_xor__v(fr_Env env, void *param, void *ret);
void sys_Int_shiftl_v(fr_Env env, void *param, void *ret);
void sys_Int_shiftr_v(fr_Env env, void *param, void *ret);
void sys_Int_shifta_v(fr_Env env, void *param, void *ret);
void sys_Int_pow_v(fr_Env env, void *param, void *ret);
void sys_Int_toStr_v(fr_Env env, void *param, void *ret);
void sys_Int_toHex_v(fr_Env env, void *param, void *ret);
void sys_Int_toRadix_v(fr_Env env, void *param, void *ret);
void sys_Int_toChar_v(fr_Env env, void *param, void *ret);
void sys_Int_toCode_v(fr_Env env, void *param, void *ret);
void sys_Int_toFloat_v(fr_Env env, void *param, void *ret);
void sys_NativeC_toId_v(fr_Env env, void *param, void *ret);
void sys_NativeC_typeName_v(fr_Env env, void *param, void *ret);
void sys_NativeC_print_v(fr_Env env, void *param, void *ret);
void sys_NativeC_printErr_v(fr_Env env, void *param, void *ret);
void sys_NativeC_stackTrace_v(fr_Env env, void *param, void *ret);
int sys_Ptr__allocSize__();
void sys_Ptr_make_v(fr_Env env, void *param, void *ret);
void sys_Ptr_stackAlloc_v(fr_Env env, void *param, void *ret);
void sys_Ptr_load_v(fr_Env env, void *param, void *ret);
void sys_Ptr_store_v(fr_Env env, void *param, void *ret);
void sys_Ptr_plus_v(fr_Env env, void *param, void *ret);
void sys_Ptr_set_v(fr_Env env, void *param, void *ret);
void sys_Ptr_get_v(fr_Env env, void *param, void *ret);
void sys_Str_format_v(fr_Env env, void *param, void *ret);

void sys_register(fr_Fvm vm) {
    fr_registerMethod(vm, "sys_Obj__allocSize__", (fr_NativeFunc)sys_Obj__allocSize__);
    fr_registerMethod(vm, "trap", sys_Obj_trap_v);
    fr_registerMethod(vm, "isImmutable", sys_Obj_isImmutable_v);
    fr_registerMethod(vm, "doFromStr", sys_Enum_doFromStr_v);
    fr_registerMethod(vm, "sys_Array__allocSize__", (fr_NativeFunc)sys_Array__allocSize__);
    fr_registerMethod(vm, "make", sys_Array_make_v);
    fr_registerMethod(vm, "size", sys_Array_size_v);
    fr_registerMethod(vm, "get", sys_Array_get_v);
    fr_registerMethod(vm, "set", sys_Array_set_v);
    fr_registerMethod(vm, "realloc", sys_Array_realloc_v);
    fr_registerMethod(vm, "arraycopy", sys_Array_arraycopy_v);
    fr_registerMethod(vm, "fill", sys_Array_fill_v);
    fr_registerMethod(vm, "finalize", sys_Array_finalize_v);
    fr_registerMethod(vm, "sys_Bool__allocSize__", (fr_NativeFunc)sys_Bool__allocSize__);
    fr_registerMethod(vm, "equals", sys_Bool_equals_v);
    fr_registerMethod(vm, "not", sys_Bool_not__v);
    fr_registerMethod(vm, "and", sys_Bool_and__v);
    fr_registerMethod(vm, "or", sys_Bool_or__v);
    fr_registerMethod(vm, "xor", sys_Bool_xor__v);
    fr_registerMethod(vm, "sys_Float__allocSize__", (fr_NativeFunc)sys_Float__allocSize__);
    fr_registerMethod(vm, "makeBits", sys_Float_makeBits_v);
    fr_registerMethod(vm, "makeBits32", sys_Float_makeBits32_v);
    fr_registerMethod(vm, "fromStr", sys_Float_fromStr_v);
    fr_registerMethod(vm, "random", sys_Float_random_v);
    fr_registerMethod(vm, "equals", sys_Float_equals_v);
    fr_registerMethod(vm, "isNaN", sys_Float_isNaN_v);
    fr_registerMethod(vm, "negate", sys_Float_negate_v);
    fr_registerMethod(vm, "mult", sys_Float_mult_v);
    fr_registerMethod(vm, "multInt", sys_Float_multInt_v);
    fr_registerMethod(vm, "div", sys_Float_div_v);
    fr_registerMethod(vm, "divInt", sys_Float_divInt_v);
    fr_registerMethod(vm, "mod", sys_Float_mod_v);
    fr_registerMethod(vm, "modInt", sys_Float_modInt_v);
    fr_registerMethod(vm, "plus", sys_Float_plus_v);
    fr_registerMethod(vm, "plusInt", sys_Float_plusInt_v);
    fr_registerMethod(vm, "minus", sys_Float_minus_v);
    fr_registerMethod(vm, "minusInt", sys_Float_minusInt_v);
    fr_registerMethod(vm, "bits", sys_Float_bits_v);
    fr_registerMethod(vm, "bits32", sys_Float_bits32_v);
    fr_registerMethod(vm, "toStr", sys_Float_toStr_v);
    fr_registerMethod(vm, "toInt", sys_Float_toInt_v);
    fr_registerMethod(vm, "toLocale", sys_Float_toLocale_v);
    fr_registerMethod(vm, "sys_Func__allocSize__", (fr_NativeFunc)sys_Func__allocSize__);
    fr_registerMethod(vm, "call", sys_Func_call_v);
    fr_registerMethod(vm, "call", sys_BindFunc_call_v);
    fr_registerMethod(vm, "sys_Int__allocSize__", (fr_NativeFunc)sys_Int__allocSize__);
    fr_registerMethod(vm, "fromStr", sys_Int_fromStr_v);
    fr_registerMethod(vm, "random", sys_Int_random_v);
    fr_registerMethod(vm, "privateMake", sys_Int_privateMake_v);
    fr_registerMethod(vm, "equals", sys_Int_equals_v);
    fr_registerMethod(vm, "compare", sys_Int_compare_v);
    fr_registerMethod(vm, "negate", sys_Int_negate_v);
    fr_registerMethod(vm, "increment", sys_Int_increment_v);
    fr_registerMethod(vm, "decrement", sys_Int_decrement_v);
    fr_registerMethod(vm, "mult", sys_Int_mult_v);
    fr_registerMethod(vm, "multFloat", sys_Int_multFloat_v);
    fr_registerMethod(vm, "div", sys_Int_div_v);
    fr_registerMethod(vm, "divFloat", sys_Int_divFloat_v);
    fr_registerMethod(vm, "mod", sys_Int_mod_v);
    fr_registerMethod(vm, "modFloat", sys_Int_modFloat_v);
    fr_registerMethod(vm, "plus", sys_Int_plus_v);
    fr_registerMethod(vm, "plusFloat", sys_Int_plusFloat_v);
    fr_registerMethod(vm, "minus", sys_Int_minus_v);
    fr_registerMethod(vm, "minusFloat", sys_Int_minusFloat_v);
    fr_registerMethod(vm, "not", sys_Int_not__v);
    fr_registerMethod(vm, "and", sys_Int_and__v);
    fr_registerMethod(vm, "or", sys_Int_or__v);
    fr_registerMethod(vm, "xor", sys_Int_xor__v);
    fr_registerMethod(vm, "shiftl", sys_Int_shiftl_v);
    fr_registerMethod(vm, "shiftr", sys_Int_shiftr_v);
    fr_registerMethod(vm, "shifta", sys_Int_shifta_v);
    fr_registerMethod(vm, "pow", sys_Int_pow_v);
    fr_registerMethod(vm, "toStr", sys_Int_toStr_v);
    fr_registerMethod(vm, "toHex", sys_Int_toHex_v);
    fr_registerMethod(vm, "toRadix", sys_Int_toRadix_v);
    fr_registerMethod(vm, "toChar", sys_Int_toChar_v);
    fr_registerMethod(vm, "toCode", sys_Int_toCode_v);
    fr_registerMethod(vm, "toFloat", sys_Int_toFloat_v);
    fr_registerMethod(vm, "toId", sys_NativeC_toId_v);
    fr_registerMethod(vm, "typeName", sys_NativeC_typeName_v);
    fr_registerMethod(vm, "print", sys_NativeC_print_v);
    fr_registerMethod(vm, "printErr", sys_NativeC_printErr_v);
    fr_registerMethod(vm, "stackTrace", sys_NativeC_stackTrace_v);
    fr_registerMethod(vm, "sys_Ptr__allocSize__", (fr_NativeFunc)sys_Ptr__allocSize__);
    fr_registerMethod(vm, "make", sys_Ptr_make_v);
    fr_registerMethod(vm, "stackAlloc", sys_Ptr_stackAlloc_v);
    fr_registerMethod(vm, "load", sys_Ptr_load_v);
    fr_registerMethod(vm, "store", sys_Ptr_store_v);
    fr_registerMethod(vm, "plus", sys_Ptr_plus_v);
    fr_registerMethod(vm, "set", sys_Ptr_set_v);
    fr_registerMethod(vm, "get", sys_Ptr_get_v);
    fr_registerMethod(vm, "format", sys_Str_format_v);
}
